project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/asantanalugo
      - icon: linkedin
        href: https://www.linkedin.com/in/asantanalugo/
format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css

editor: visual

